language: node_js
node_js:
    - "node"
branches:
  only:
  - master
install:
  - npm install --no-save
script:
  - npm run lint
  - npm run test
  - npm run build
notifications:
    email:
        - serginator@gmail.com
